### Register User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstname": "Alex",
  "lastname": "Liu",
  "email":  "test2@mail.com",
  "password": "password",
  "role":  "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Query the Demo endpoint
GET http://localhost:8080/demo-controller
Authorization: Bearer {{auth-token}}
